### ISSUE TITLE
Checkpoint state dict does not match the model and some KeyErrors

### ISSUE THREAD

**Issue by juyebshin** [Mrmoore98/VectorMapNet_code#14]
Thank you for the public release of your code! I was evaluating the VectorMapNet model with the checkpoint provided and faced some problems as in the screen above. 

1. Loaded state dict does not match the model
![image](https://user-images.githubusercontent.com/47021776/209623447-0584af84-1626-4b70-9f65-1be47fa5cfc3.png)

2. KeyErrors in https://github.com/Mrmoore98/VectorMapNet_code/blob/47ed228de3b1441fb5ae31a573e87affcb01129e/plugin/datasets/pipelines/map_transform.py#L200

![image](https://user-images.githubusercontent.com/47021776/210191475-90bfe547-ce5f-4a0e-9681-d4b66ab0f947.png)

Any idea how to solve these?

**Comment by juyebshin** [comment]
For second one, looks like shapely version conflict, 😭

**Comment by juyebshin** [comment]
Looks like, for second issue, Shapely version conflict 😭

**Comment by juyebshin** [comment]
In the code below
https://github.com/Mrmoore98/VectorMapNet_code/blob/47ed228de3b1441fb5ae31a573e87affcb01129e/plugin/datasets/pipelines/map_transform.py#L200

the variable `o` is the index of the matching tree geometry, so additional indexing is needed, something like this:
```
for o in tree.query(pgeom):
    o = ped_geoms[o] # added
    o_idx = index_by_id[id(o)]
```

**Comment by seva1232** [comment]
Hello! Thank you for the answer! Do you have any ideas about the problem with state dict?

**Comment by Mrmoore98** [comment]
> In the code below
> 
> https://github.com/Mrmoore98/VectorMapNet_code/blob/47ed228de3b1441fb5ae31a573e87affcb01129e/plugin/datasets/pipelines/map_transform.py#L200
> 
> the variable `o` is the index of the matching tree geometry, so additional indexing is needed, something like this:
> 
> ```
> for o in tree.query(pgeom):
>     o = ped_geoms[o] # added
>     o_idx = index_by_id[id(o)]
> ```

Thank you for pointing out this issue.
the shapely version I used is 1.8. I didn't foresee It upgrade recently. I added it in the requirement.txt.
