### ISSUE TITLE
anyone has the similar problem like this？

### ISSUE THREAD

**Issue by scream68** [Mrmoore98/VectorMapNet_code#17]
'MultiPolygon' object is not iterable

**Comment by secret104278** [comment]
@scream68 how did you solve this?

**Comment by secret104278** [comment]
`pip install shapely==1.8.5` save my day

**Comment by scream68** [comment]
> @scream68 how did you solve this?

check the key 'MultiPolygon' ‘s value，for it not enough for iteration，maybe use ‘Polygon’ list to instead  is a not bad choice。If you find a better solution, please reply。
