### ISSUE TITLE
the problem in map_transform.py

### ISSUE THREAD

**Issue by scream68** [Mrmoore98/VectorMapNet_code#19]
in
def poly_geoms_to_vectors(self, polygon_geoms: list):
      for geom in polygon_geoms:
            for poly in geom:
                exteriors.append(poly.exterior)

show that 
'MultiPolygon' object has no attribute 'exterior'

i check the gorms:
[<MULTIPOLYGON (((5.806 -12.166, 6.497 -12.139, 16.382 -11.565, 19.506 -11.43...>]
[<MULTIPOLYGON (((15.928 -12.742, 16.621 -15, 12.609 -15, 8.42 -15, 8.306 -15...>]
[<MULTIPOLYGON (((-30 -6.392, -30 -4.398, -29.721 -4.36, -26.824 -3.96, -24.6...>]
[<MULTIPOLYGON (((-27.27 -8.146, -26.997 -8.141, -26.404 -8.041, -25.868 -7.7...>]

whether this problem arise for my use the mini-data(nuscenes) or not

hope for some reply

**Comment by dq2b25** [comment]
I get the same problem, how to solve it?
