### ISSUE TITLE
When is the code open source?

### ISSUE THREAD

**Issue by funcici** [Mrmoore98/VectorMapNet_code#2]
Hey, I pay attention to your work, which is very excellent. When is the code open source? Look forward to your reply.

**Comment by sgzqc** [comment]
+1

**Comment by joeloren** [comment]
+1

**Comment by joeloren** [comment]
+1

**Comment by Mrmoore98** [comment]
After a conference accepts our paper, we will open-source the code. Currently, the detailed model structure is still being tuned.

**Comment by quangnhat185** [comment]
Hey @Mrmoore98,
First of all very impressing work you got here.
Could you give an estimation until when the code would be open-sourced?

**Comment by Mrmoore98** [comment]
we have provided a preliminary version of our code. We will refine it in next few weeks.
