### ISSUE TITLE
Bad performance on nuScenes v1.0-mini

### ISSUE THREAD

**Issue by Naniko0213** [Mrmoore98/VectorMapNet_code#28]
Hi! Thanks for making your code open! I tried use this code to test its performance on nuScenes v1.0 mini, but I got a bad performance about only 1% map after 130 epochs. My steps are as follows:

1.  Data process. I downloaded nuScenes v1.0 mini (3.88G) and the map expansion(0.38G). And I run **python tools/data_converter/nuscenes_converter.py --data-root your/dataset/nuScenes/ --version v1.0-mini**, getting **two .pkl file** successfully. My datasets directory is as follows:
![image](https://user-images.githubusercontent.com/73332537/221073140-9ceb5fd4-a049-4df8-ae87-50647016887b.png)

2.  Training. I set **samples_per_gpu** as **2** and **works_per_gpu** as **8**. **No other changes about the configs**. And I run **python tools/train.py configs/vectormapnet.py**. There is no mistake during training, but the mAP is low. 
![image](https://user-images.githubusercontent.com/73332537/221073861-4aea82f4-225f-436e-8baf-714313c58ec0.png)

Here is the **log file**: https://naniko.obs.cn-central-221.ovaijisuan.com/VectorMap/result.zip

Did I do something wrong ?

**Comment by scream68** [comment]
i got the similar result.  did u test success？（contain the function of show）.  hope for sharing

**Comment by Naniko0213** [comment]
> i got the similar result. did u test success？（contain the function of show）. hope for sharing

I tried this model on the full dataset and got the expected mAP. For mini-dataset, it only have 10 scenes, which may not enough for the training process. So if u want to try, u can use mini-dataset to debug and use the full dataset to check whether the model works.

**Comment by Sweetylrx** [comment]
I trained the model on a single RTX 3090, it cannot achieve the reported mAP? I do not know why?
