### ISSUE TITLE
Some question in paper

### ISSUE THREAD

**Issue by ponyyangzeng** [Mrmoore98/VectorMapNet_code#4]
1. Does 1 query be responsible for 1 instance lane?
2. How to predict all points of a lane in parallel?
3. In key points detection stage, is output shape like (N, k, 2), (N, _cls_num_), where N is _num_query_, k is _num_key_point_ ?
4. After hungarian matching, will only matched query be used for polyline generation?

**Comment by Mrmoore98** [comment]
A1: one element query corresponding to one instance, and one element query has three keypoint query which correspond to a keypoint.
A2: polyline generator autoregressively generate each point of the lane, but we can decode the all lanes in parallel.
A3: Yes
A4: Yes
