### ISSUE TITLE
Evaluation error

### ISSUE THREAD

**Issue by colahe** [Mrmoore98/VectorMapNet_code#44]
Hi, when i evaluate this network, i got this error, ( RuntimeError: CUDA out of memory. Tried to allocate 1.05 GiB (GPU 0; 5.80 GiB total capacity; 2.91 GiB already allocated; 686.94 MiB free; 3.72 GiB reserved in total by PyTorch)), do you have some suggestions?

**Comment by BatyrM** [comment]
I am facing the same issue @colahe, can you please tell me how did you solve it?
