### ISSUE TITLE
Some question about training

### ISSUE THREAD

**Issue by Timer-x** [Mrmoore98/VectorMapNet_code#5]
Were Map Element Detector and Polyline Generator trained simultaneously？Or Map Element Detector should be trained first？Looking forward to your kindly reply

**Comment by Mrmoore98** [comment]
You can train them simultaneously. Welcome to check our new revised paper.

**Comment by Alexanderisgod** [comment]
i just trained the map element detector only, however, the results showed that the loss wouldn't converge.
