### ISSUE TITLE
R50 pretrain model

### ISSUE THREAD

**Issue by kvjia** [Mrmoore98/VectorMapNet_code#7]
Hi！Could you provide the r50 pretrain model used in the config? I use a r50 with ImageNet pretrain, but I got a bad result with mAP 0.34.

**Comment by Mrmoore98** [comment]
Do you mean you trained the model from scratch and got bad results? 
the R50 pretrain model's cfg is provided in config.
Currently, the training pipeline have some problem, we are fixing it.
You can get the results showed in this repo by loading the checkpoint we provided.

**Comment by kvjia** [comment]
OK. Thank you！
