### ISSUE TITLE
map visualization

### ISSUE THREAD

**Issue by Alexanderisgod** [Mrmoore98/VectorMapNet_code#8]
when i gonna to visualize the map, i cann't find the cfg file? could you release it, please?
![2022-11-07 10-45-52 的屏幕截图](https://user-images.githubusercontent.com/41862202/200216098-9a016aa9-69fa-4cc0-be4d-294e57fa9960.png)

**Comment by Mrmoore98** [comment]
We haven't provide visualization code, as it's not our contribution. But maybe we will provide a simple code to visualize our results in next week.

**Comment by Alexanderisgod** [comment]
> We haven't provide visualization code, as it's not our contribution. But maybe we will provide a simple code to visualize our results in next week.
Could you tell me the origin source. i have try it on my own. But the road_segment, road_block, lane, lane_connector are so confused.  I want to extract centerlines of the usually 'road', do you have any suggestion?
![map](https://user-images.githubusercontent.com/41862202/200467815-cccbacb3-2b9a-4f6e-a0cb-48726ae12080.jpg)

**Comment by Mrmoore98** [comment]
You can let the model to learn the centerlines and then predict them. VectorMapNet is supported to predicted centerllines. We have verified this. We don't have rule based method to generate centerlines.

**Comment by alfredgu001324** [comment]
@Alexanderisgod Hi thanks for posting this issue. I am also struggling with visualizing the output. I am able to run the code until the point where they set vectors=data['vectors'] and it showed a key error. I have been exploring but did not really find a place where this 'vectors' key is initialized. I really appreciate your help, thanks！

**Comment by fentuoli** [comment]
> > We haven't provide visualization code, as it's not our contribution. But maybe we will provide a simple code to visualize our results in next week.
> > Could you tell me the origin source. i have try it on my own. But the road_segment, road_block, lane, lane_connector are so confused.  I want to extract centerlines of the usually 'road', do you have any suggestion?
> > ![map](https://user-images.githubusercontent.com/41862202/200467815-cccbacb3-2b9a-4f6e-a0cb-48726ae12080.jpg)

Hello, I also struggled to visualize the results but failed, can you share your revised code? I'll really appreciate your help, thanks!

**Comment by aidadgy** [comment]
> @Alexanderisgod Hi thanks for posting this issue. I am also struggling with visualizing the output. I am able to run the code until the point where they set vectors=data['vectors'] and it showed a key error. I have been exploring but did not really find a place where this 'vectors' key is initialized. I really appreciate your help, thanks！
hi，@alfredgu001324，May I ask how you achieved visualization

**Comment by alfredgu001324** [comment]
Hi, sorry it's been a year and I do not quite remember it anymore
