### ISSUE TITLE
Result visualization

### ISSUE THREAD

**Issue by quangnhat185** [Mrmoore98/VectorMapNet_code#9]
Hi, I managed  to run your evaluation script and got the same result. 
In the next step I would like to visualize the predicted map as BEV figures which are shown in the paper. 
Can you tell me which scripts do you use for this task?

Thank you a lot

**Comment by Mrmoore98** [comment]
We haven't provide visualization code, as it's not our contribution. But maybe we will provide a simple code to visualize our results in next week.

**Comment by stefanopini** [comment]
Hi @Mrmoore98, any updates on this? A visualization tool would be very useful to assess the quality of the results.

**Comment by aidadgy** [comment]
> We haven't provide visualization code, as it's not our contribution. But maybe we will provide a simple code to visualize our results in next week.
Hi @Mrmoore98, Is there a visual script provided
